import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IssueBookForm.java
 *
 * Created on 11 Oct, 2014, 6:31:47 PM
 */
/**
 *
 * @author mridul
 */
public class IssueBookForm extends javax.swing.JFrame {

    /** Creates new form IssueBookForm */
    public IssueBookForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        C_Book = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        T_ID = new javax.swing.JTextField();
        T_BID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        T_MID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        C_Member = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        T_DOI = new javax.swing.JTextField();
        B_Issue = new javax.swing.JButton();
        B_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        C_Book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_BookActionPerformed(evt);
            }
        });

        jLabel1.setText("Issue ID");

        jLabel2.setText("Book ID");

        jLabel3.setText("Member ID");

        C_Member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C_MemberActionPerformed(evt);
            }
        });

        jLabel4.setText("Date of Issue");

        B_Issue.setText("Issue");
        B_Issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_IssueActionPerformed(evt);
            }
        });

        B_Cancel.setText("Cancel");
        B_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(T_MID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C_Member, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(T_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(T_BID, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(C_Book, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(T_DOI, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(B_Issue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_Cancel)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(T_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(T_BID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_Book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(T_MID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(C_Member, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(T_DOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B_Issue)
                    .addComponent(B_Cancel))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void B_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CancelActionPerformed
this.dispose();
}//GEN-LAST:event_B_CancelActionPerformed

private void C_BookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_BookActionPerformed
    Connection con = DBC.ConnectDB();
    
    ResultSet R= DBC.getTable(con, "select * from books where bname='" + C_Book.getSelectedItem() + "'");
    try{
        R.first();
        int bid = R.getInt("bid");
        T_BID.setText(bid+"");
        
        }catch(Exception e){}
    DBC.DisconnectDB(con);
}//GEN-LAST:event_C_BookActionPerformed

private void C_MemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C_MemberActionPerformed
Connection con = DBC.ConnectDB();
    
    ResultSet R= DBC.getTable(con, "select * from members where name='" + C_Member.getSelectedItem() + "'");
    try{
        R.first();
        int mid = R.getInt("id");
        T_MID.setText(mid+"");
        
        }catch(Exception e){}
    DBC.DisconnectDB(con);
}//GEN-LAST:event_C_MemberActionPerformed

private void B_IssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_IssueActionPerformed
    Connection con = DBC.ConnectDB();
    if ((C_Book.getSelectedItem()+"").equals("N/A")==false)
    {
        DBC.ExecuteSQL(con, "insert into issue values(" + T_ID.getText() + "," + T_BID.getText() + "," + T_MID.getText() + ",'" + T_DOI.getText()+"')");
        DBC.ExecuteSQL(con,"update members set issued=issued+1 where id=" + T_MID.getText());
        DBC.ExecuteSQL(con, "update books set available=0 where bid=" + T_BID.getText());
    }
    DBC.DisconnectDB(con);
    this.dispose();
}//GEN-LAST:event_B_IssueActionPerformed

private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    this.setTitle("Issue Book");
}//GEN-LAST:event_formWindowActivated

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    this.setLocationRelativeTo(null);
}//GEN-LAST:event_formWindowOpened

public void UpdateFields(int bid)
{
    
    Date now = new Date(); 
    SimpleDateFormat formatter = new SimpleDateFormat( "yyyy-MM-dd" );
    String DOI =formatter.format( now ) ; 
    
    Connection con = DBC.ConnectDB();
    
        
            T_ID.setText(""+(getMaxID()+1));
            
            T_DOI.setText(DOI);
            T_MID.setText("1000");
            //Availability can't be changed from here.
            populateCombo();
    if (bid!=-1)
    {   ResultSet R = DBC.getTable(con, "Select * from books where bid=" + bid);
        try{
            R.first();
            String bname = R.getString("bname");
            C_Book.setSelectedItem(bname);
            }catch(Exception e){}
    }
    else
    {
        ResultSet R = DBC.getTable(con, "Select * from books");
        try{
            R.first();
            String bname = R.getString("bname");
            bid=R.getInt("bid");
            C_Book.setSelectedItem(bname);
            }catch(Exception e){}
    }
    
        T_BID.setText(bid+"");  //Set bid text after conforming it exists
        
    DBC.DisconnectDB(con);
    this.setVisible(true);
}

private void populateCombo()
{int i=0;
        Connection con = DBC.ConnectDB();
        ResultSet R1 = DBC.getTable(con, "select Count(*)'count' from books");
        ResultSet R2 = DBC.getTable(con, "select Count(*)'count' from members");
        try{
            R1.first();
            R2.first();
            int bCount = R1.getInt("count");
            int mCount = R2.getInt("count");
            
            R1.close();
            R2.close();
       R1 = DBC.getTable(con, "select * from books");
       R2 = DBC.getTable(con, "select * from members");
            String[] bNames = new String [bCount];
            String[] mNames = new String [mCount];
            
            while(R1.next())
            {
                if (R1.getInt("available") == 1)
                bNames[i] = R1.getString("bname");
                else 
                    bNames[i]="N/A";
                i++;
            }
            i=0;
            while (R2.next())
            {
                mNames[i] = R2.getString("name");
                i++;
            }
            C_Book.setModel(new javax.swing.DefaultComboBoxModel(bNames));
            C_Member.setModel(new javax.swing.DefaultComboBoxModel(mNames));
            
            }catch(Exception e){}
        DBC.DisconnectDB(con);
}

private int getMaxID()
{
     int maxID=0;
    Connection con = DBC.ConnectDB();
    ResultSet R = DBC.getTable(con, "Select max(id)'id' from issue");
        
    try {
        R.first();
            maxID=R.getInt("id");
            return maxID;
        } catch (Exception e) {
            System.out.println(e);
        }
    
DBC.DisconnectDB(con);
        return 0;
}



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IssueBookForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IssueBookForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Cancel;
    private javax.swing.JButton B_Issue;
    private javax.swing.JComboBox C_Book;
    private javax.swing.JComboBox C_Member;
    private javax.swing.JTextField T_BID;
    private javax.swing.JTextField T_DOI;
    private javax.swing.JTextField T_ID;
    private javax.swing.JTextField T_MID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
